// apps_loops/react/dommanip/src/Table.js
import "./Table.css";

const Table = ({ rows }) => {
  return (
    <table className="table">
      <tbody>
        {rows.map(row => (
          <tr className="table__row">
            <td className="table__cell">{row.rowId}</td>
            <td className="table__cell">{row.value}</td>
          </tr>))}
      </tbody>
    </table>
  );
}

export default Table;

// apps_loops/angular/dommanip/src/app/table/table.component.ts
import { Component, Input } from '@angular/core';
import { Row } from 'src/types/row';

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css']
})
export class TableComponent {
  @Input() rows: Array<Row> = [];
}

<table class="table">
  <tbody>
    <tr class="table__row" *ngFor="let row of rows">
      <td class="table__cell">{{ row.rowId }}</td>
      <td class="table__cell">{{ row.value }}</td>
    </tr>
  </tbody>
</table>
